### ISSUE TITLE
Plugin request: PHPmyadmin

### ISSUE THREAD

**Issue by Bugsbane** [arkOScloud/genesis#454]
As soon as you start dealing with any web app that uses MariaDB / Mysql, sooner or later any user who doesn't know the occult knowledge of command line SQL ends up needing PHPmyadmin.

**Comment by peakwinter** [comment]
This is a great feature but I don't think there will be enough users to warrant including it in the core Databases pane of arkOS itself. So I will leave this up to contributors who may want to contribute a PHPMyAdmin application for arkOS.

**Comment by peakwinter** [comment]
arkOScloud/applications#36
