### ISSUE TITLE
[enhancement] Full server backup via Genesis plugin

### ISSUE THREAD

**Issue by Bugsbane** [arkOScloud/genesis#459]
Especially while things are experimental and somewhat unstable, having the ability to back up the entire server would be very useful. Eventually, it would be rgeat to have some kind of distributed system letting backups be stored (via TahoeFS?) across other trusted arkOS nodes, but for the moment, even just something that created one big tarball in a location that avoided backups being included in backups, would be the 80% solution for minimal effort.

This would include:
the /srv folder
all databases
All Genesis files
etc.

...but would not include the operating system itself. Basically, it would be everything needed to restore genesis and the installed plugins to their previous state on the host OS. A GUI for recovering via a backup would be great, but the ability to backup is the only first crucial step.

**Comment by peakwinter** [comment]
Data backups are now a thing in 0.7. I will see about adding a "Backup All" button in 0.7.1 that automatically does all data backups at once.

**Comment by peakwinter** [comment]
arkOScloud/core#15
