### ISSUE TITLE
cannot view genesis webUI properly on android

### ISSUE THREAD

**Issue by amo13** [arkOScloud/genesis#511]
With both tablet and phone (android 4.4.4) I am not able to view the genesis webpage correctly. I cannot access the buttons normally found on the right upper corner like the tools or the admin stuff. I e.g. cannot access the filesystems page to mount an external drive.
Unfortunately I am not able to append a screenshot right now. If you need one I would try again later on.

**Comment by peakwinter** [comment]
Thanks for the reminder; the default UI in 0.6.x isn't very responsive-friendly, though this should be somewhat better in 0.7.
