### ISSUE TITLE
Queue application installs

### ISSUE THREAD

**Issue by rzippert** [arkOScloud/genesis#527]
Hello!

Been testing 0.7.1 and noticed that the interface allows the user to request for multiple installs simultaneously, but kraken will fail to obtain a lock for pacman and then installs will fail with no clear message.

Shouldn't apps be lined up for installation as the user selects them, instead of instant install?

**Comment by peakwinter** [comment]
Hi there,

Yes that is indeed desired behaviour -- I remember running into this case in the past but putting its resolution off until later ;) I'll take a stab at it for 0.8. Thanks!

**Comment by peakwinter** [comment]
Primary issue: arkOScloud/core#4
